const products = [
  {
    id: 0,
    section: 'Heladeria',
    title: 'Helado de yogurt',
    img: '/images/heladoYogurt1.jpg',
    description: 'Helado natural de yogurt con el topping que desees',
    options: [ 'Con fruta', 'Sin fruta'],
    variations: [
      {
        name: '1 topping',
      },
      {
        name: '2 toppings',
        price: 4700,
      },
      {
        name: '3 toppings',
        price: 5200,
      }
    ],
    price: 3800,
  },
  {
    id: 1,
    section: 'Heladeria',
    title: 'Malteada',
    img: '/images/malteada1.jpg',
    description: 'Disfruta de una de nuestras malteadas artesanales.',
    options: ['Chocolate', 'Fresa', 'Vainilla'],
    price: 8800,
  },
  {   
    id: 2,
    section:'Heladeria',
    title: 'Helado 1 bola',
    img: '/images/helado1Bola.jpg',
    description: 'Disfruta  ',
    options: [],
    variations: [],
    price: 160000,
  },
  {
    id: 3,
    section: 'Heladeria',
    title: 'Porción de torta con heladeria',
    img: '/images/tortaConHelado.jpg',
    description: 'Ven y prueba nuestro combo de torta con helado',
    options: '',
    variations: '',
    price: '6000',
  },
  {
    id: 4,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 5,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 6,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 7,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 8,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 9,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 10,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 11,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 12,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 13,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 14,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 15,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 16,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 17,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 18,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
  {
    id: 19,
    section: '',
    title: '',
    img: '',
    description: '',
    options: '',
    variations: '',
    price: '',
  },
];

module.exports = products;